from .resolution_matrix import NODE_CLASS_MAPPINGS as RESOLUTION_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as RESOLUTION_DISPLAY
from .resize_image import NODE_CLASS_MAPPINGS as RESIZE_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as RESIZE_DISPLAY

# Combine mappings from all nodes
NODE_CLASS_MAPPINGS = {**RESOLUTION_MAPPINGS, **RESIZE_MAPPINGS}
NODE_DISPLAY_NAME_MAPPINGS = {**RESOLUTION_DISPLAY, **RESIZE_DISPLAY}

WEB_DIRECTORY = "./web"

__all__ = [
    "NODE_CLASS_MAPPINGS",
    "NODE_DISPLAY_NAME_MAPPINGS",
    "WEB_DIRECTORY",
]
